name = "Normalization"
uuid = "be38d6a3-8366-4a42-ad57-222272b5bbe7"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com>"]
version = "0.7.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
DataFramesExt = "DataFrames"
DimensionalDataExt = "DimensionalData"
UnitfulExt = "Unitful"

[compat]
Accessors = "0.1"
DataFrames = "1"
DimensionalData = "0.23, 0.24, 0.25, 0.26, 0.27"
StatsAPI = "1"
Unitful = "1"
julia = "1.9"
