name = "Normalization"
uuid = "be38d6a3-8366-4a42-ad57-222272b5bbe7"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com>"]
version = "0.3.3"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
UnitfulExt = "Unitful"

[compat]
JuliennedArrays = "0.3, 0.4"
Accessors = "0.1"
StatsAPI = "1"
Unitful = "1"
julia = "1.9"
