name = "Normalization"
uuid = "be38d6a3-8366-4a42-ad57-222272b5bbe7"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com>"]
version = "0.3.1"

[deps]
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
JuliennedArrays = "0.3, 0.4"
julia = "1.6"
